name: Build VEH DLL and Injector (MSVC)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up MSVC Developer Command Prompt
      uses: ilammy/msvc-dev-cmd@v1

    - name: Build DLL and EXE with MSVC
      shell: cmd
      run: |
        mkdir build
        cl /LD /EHsc VEHSkipPatch.cpp /Fe:build\VEHSkipPatch.dll
        cl /EHsc Injector.cpp /Fe:build\Injector.exe

    - name: Upload compiled files
      uses: actions/upload-artifact@v4
      with:
        name: patch-build
        path: build/
